name: Publish Package to PyPI

on:
    push:
        tags:
            - "v*"

jobs:
    Deploy:
        name: Deploy to PyPI
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            
            - name: Install Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.9"
            
            - name: Install Dependencies
              run: |
                    python -m pip install pip --upgrade pip
                    pip install build
            
            - name: Build Package
              run: python -m build

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                password: ${{ secrets.PYPI_TOKEN }}