steps:
- uses: actions/checkout@v4
- name: Set up Python
  uses: actions/setup-python@v5
  with:
    python-version: '3.x'
- name: Test with pytest
  run: |
    pip install pytest pytest-cov
    pytest tests/
